//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIRA_Team_Hours
{
    using System;
    using System.Collections.Generic;
    
    public partial class JIRA_Team
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string DisplayName { get; set; }
        public string Group { get; set; }
        public Nullable<int> ActiveSprint { get; set; }
        public Nullable<double> BurntHours { get; set; }
        public Nullable<double> RemainingHours { get; set; }
        public Nullable<System.DateTime> DtLastModified { get; set; }
    }
}
