//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JIRA_Team_Hours
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JIRA_Team> JIRA_Team { get; set; }
    
        [DbFunction("TestEntities", "parseJSON")]
        public virtual IQueryable<parseJSON_Result> parseJSON(string jSON)
        {
            var jSONParameter = jSON != null ?
                new ObjectParameter("JSON", jSON) :
                new ObjectParameter("JSON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<parseJSON_Result>("[TestEntities].[parseJSON](@JSON)", jSONParameter);
        }
    
        [DbFunction("TestEntities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string s, string sep)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            var sepParameter = sep != null ?
                new ObjectParameter("sep", sep) :
                new ObjectParameter("sep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[TestEntities].[SplitString](@s, @sep)", sParameter, sepParameter);
        }
    
        public virtual int BulkInsertPCProperty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BulkInsertPCProperty");
        }
    
        public virtual ObjectResult<EventCodesTest_Result> EventCodesTest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EventCodesTest_Result>("EventCodesTest");
        }
    
        public virtual ObjectResult<EventCodesTestQA_Result> EventCodesTestQA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EventCodesTestQA_Result>("EventCodesTestQA");
        }
    
        public virtual ObjectResult<EventCodesTestUAT_Result> EventCodesTestUAT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EventCodesTestUAT_Result>("EventCodesTestUAT");
        }
    
        public virtual ObjectResult<HttpRequest_Result> HttpRequest(string url, string headers, ObjectParameter response, ObjectParameter responseHeaders, ObjectParameter errorResponse, ObjectParameter cookie, Nullable<int> connectTimeout, Nullable<bool> outputResponse, string httpMethod, string requestBody)
        {
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            var headersParameter = headers != null ?
                new ObjectParameter("headers", headers) :
                new ObjectParameter("headers", typeof(string));
    
            var connectTimeoutParameter = connectTimeout.HasValue ?
                new ObjectParameter("connectTimeout", connectTimeout) :
                new ObjectParameter("connectTimeout", typeof(int));
    
            var outputResponseParameter = outputResponse.HasValue ?
                new ObjectParameter("outputResponse", outputResponse) :
                new ObjectParameter("outputResponse", typeof(bool));
    
            var httpMethodParameter = httpMethod != null ?
                new ObjectParameter("httpMethod", httpMethod) :
                new ObjectParameter("httpMethod", typeof(string));
    
            var requestBodyParameter = requestBody != null ?
                new ObjectParameter("requestBody", requestBody) :
                new ObjectParameter("requestBody", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HttpRequest_Result>("HttpRequest", urlParameter, headersParameter, response, responseHeaders, errorResponse, cookie, connectTimeoutParameter, outputResponseParameter, httpMethodParameter, requestBodyParameter);
        }
    
        public virtual ObjectResult<JiraMySprintHours_Result> JiraMySprintHours(Nullable<int> sprint, string user)
        {
            var sprintParameter = sprint.HasValue ?
                new ObjectParameter("sprint", sprint) :
                new ObjectParameter("sprint", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JiraMySprintHours_Result>("JiraMySprintHours", sprintParameter, userParameter);
        }
    
        public virtual ObjectResult<string> JiraTeamSprintHours()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("JiraTeamSprintHours");
        }
    
        public virtual ObjectResult<SeleniumMethodConvert_Result> SeleniumMethodConvert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeleniumMethodConvert_Result>("SeleniumMethodConvert");
        }
    }
}
